name: Hello World!
descrition:  Greet someone and record the time
author: GitHub Actions

inputs:
  who-to-greet:
    descrition: Who to greet
    required: true
    default: World

outputs:
  time:
    description: The tine we Greeted you

runs: 
  using: docker
  image: Dokerfile
  args:
    - ${{ inputs.who-to-greet }}