name: Greeting on variable day
on: workflow_dispatch
env: 
    DAY_OF_THE_WEEK: MONDAY

jobs:
    greeting_job:
        runs-on: ubuntu-latest
        env:
            GREETING: Hello
        steps: 
            - name: "Say hello Mona it's Monday"
              run: echo "$GREETING $First_Name. Today is $DAY_OF_THE_WEEK!"
              env: 
                First_Name: Paulo